config/routes.rb
WordsRelatedTo::Application.routes.draw do
  root 'words#index'

  resources :words do
    member do
      resources :related_words, only: [:create, :new]
    end
  end

end

app/models/relation.rb
class Relation < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_and_belongs_to_many :related_words, class_name: 'Word', foreign_key: 'related_id', association_foreign_key: 'relating_id', join_table: :relations
  has_and_belongs_to_many :relating_words, class_name: 'Word', foreign_key: 'relating_id', association_foreign_key: 'related_id', join_table: :relations

  def to_s
    word
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/related_words_controller.rb
class RelatedWordsController < ApplicationController
  before_action :set_word, only: [:create, :new]
  before_action :set_related_word, only: [:create]

  def create
    @word.related_words << @related_word
    respond_to do |format|
      format.html { redirect_to @word }
    end
  end

  def new
  end

  private
    def set_word
      @word = Word.find(params[:id])
    end

    def set_related_word
      @related_word = Word.find_or_create_by word: params[:word]
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :'data-ng-app' => 'WordsRelatedTo' }
  %head
    %title WordsRelatedTo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = javascript_include_tag 'arbor'
    = javascript_include_tag 'arbor-renderer'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cardo:400,700,400italic', media: 'all'
    = csrf_meta_tags
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1.0' }
  %body
    = yield

app/views/related_words/new.html.haml
= form_tag related_words_path @word do
  = text_field_tag :word
  = submit_tag 'Add word'

app/views/words/_form.html.haml
= form_for(@word) do |f|
  - if @word.errors.any?
    #error_explanation
      %h2
        = pluralize(@word.errors.count, "error")
        prohibited this word from being saved:
      %ul
      - @word.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :word
    = f.text_field :word
  .actions
    = f.submit

app/views/words/edit.html.haml
%h1 Editing word
= render 'form'
= link_to 'Show', @word
|
= link_to 'Back', words_path

app/views/words/index.html.haml
%div{ :'ng-view' => '' }

%script{ type: 'text/ng-template', id: 'search.html' }
  %input{ type: 'text', :'data-ng-model' => 'wordFilter.word' }
  .word{ :'data-ng-repeat' => 'word in allWords | filter:wordFilter ' }
    <a href="/#/{{ word.id }}">{{ word.word }}</a>

%script{ type: 'text/ng-template', id: 'word.html' }
  %div{ :'data-wrt-word-graph' => '' }

%script{ type: 'text/ng-template', id: 'word-graph.html' }
  %article.word
    .word-graph

      %h1
        %span.word{ :'data-word-id' => '{{ word.id }}',
                    :'data-ng-controller' => 'WordController' }
          {{ word.word }}

      %ul
        %li{ class: 'word',
             :'data-word-id' => '{{ related_word.id }}',
             :'data-ng-repeat' => 'related_word in word.related_words' }
          <a href="/#/{{ related_word.id }}">{{ related_word.word }}</a>

app/views/words/new.html.haml
%h1 New word
= render 'form'
= link_to 'Back', words_path

app/views/words/show.html.haml
%article.word
  .word-graph

    %h1
      %span.pre Words related to
      %span.word{:'data-word-id' => @word.id, :'data-word-url' => word_url(@word)}
        = @word

    %ul
      - @word.related_words.each do |w|
        %li{ class: 'word',
             :'data-word-id' => w.id,
             :'data-word-url' => word_url(w) }
          = link_to w, word_path(w)

    .word.add{ :'data-word-id' => 'add' }
      = form_tag related_words_path @word do
        = text_field_tag :word
        = submit_tag '+'

= link_to 'Edit', edit_word_path(@word)
= link_to 'Back', words_path
%p#notice= notice